# Generated by Django 5.0.1 on 2024-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_carusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='postapp.tag'),
        ),
    ]
